<a href="https://colab.research.google.com/github/ChonnaveeSuk/intro-Data-Science-KMUTNB/blob/main/Workshop_Lecture2_Python_Basic_Data_Sci(11Jul2023).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
import pandas as pd


In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import seaborn as sns

In [ ]:
import plotly.express as px

In [ ]:
w = np.array([2.,1.5]) ; #W1 ,W2
w


array([2. , 1.5])

In [ ]:
w

In [ ]:
array ([2.,1.5])

In [ ]:
x = np.array ([2.,1.5])  #X1 ,X2
x

array([2. , 1.5])

In [ ]:
#we would like to multiple w*x => y


In [ ]:
y = w*x  #this i s pointwise multiplication W1*X1 , W2*X2
y

array([4.  , 2.25])

We to multiply two vectors as dot product.

In [ ]:
y = np.dot(w,x)  #[w1,w2] . [x1,x2] => [W1*X1 + W2*X2]
y #show y

6.25

In [ ]:
W = np.array ([[1.,2.],[3.,4.]])
W

array([[1., 2.],
       [3., 4.]])

In [ ]:
x

array([2. , 1.5])

In [ ]:
y = np.dot(W,x) #1*2+2*1.5 , 3*2+4*1.5

IMPORT PANDAS

In [ ]:
!ls  #list the file in the current directory


iris.data  sample_data


In [ ]:
iris = pd.read_csv("iris.data", sep="," , header=None )

In [ ]:
!cat iris.data

5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5.0,3.6,1.4,0.2,Iris-setosa
5.4,3.9,1.7,0.4,Iris-setosa
4.6,3.4,1.4,0.3,Iris-setosa
5.0,3.4,1.5,0.2,Iris-setosa
4.4,2.9,1.4,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa
5.4,3.7,1.5,0.2,Iris-setosa
4.8,3.4,1.6,0.2,Iris-setosa
4.8,3.0,1.4,0.1,Iris-setosa
4.3,3.0,1.1,0.1,Iris-setosa
5.8,4.0,1.2,0.2,Iris-setosa
5.7,4.4,1.5,0.4,Iris-setosa
5.4,3.9,1.3,0.4,Iris-setosa
5.1,3.5,1.4,0.3,Iris-setosa
5.7,3.8,1.7,0.3,Iris-setosa
5.1,3.8,1.5,0.3,Iris-setosa
5.4,3.4,1.7,0.2,Iris-setosa
5.1,3.7,1.5,0.4,Iris-setosa
4.6,3.6,1.0,0.2,Iris-setosa
5.1,3.3,1.7,0.5,Iris-setosa
4.8,3.4,1.9,0.2,Iris-setosa
5.0,3.0,1.6,0.2,Iris-setosa
5.0,3.4,1.6,0.4,Iris-setosa
5.2,3.5,1.5,0.2,Iris-setosa
5.2,3.4,1.4,0.2,Iris-setosa
4.7,3.2,1.6,0.2,Iris-setosa
4.8,3.1,1.6,0.2,Iris-setosa
5.4,3.4,1.5,0.4,Iris-setosa
5.2,4.1,1.5,0.1,Iris-setosa
5.5,4.2,1.4,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa
5.0,3.2,1.2,0.2,Iris

In [ ]:
iris.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [ ]:
attributes = ["sepal_length","sepal_width","petal_length","petal width","species"]

In [ ]:
iris = pd.read_csv("iris.data", sep="," , header=None , names=attributes )

In [ ]:
iris.head() #show on top row in 5

sepal_length  sepal_width  petal_length  petal width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
iris.tail()  #show the last 5 row

sepal_length  sepal_width  petal_length  petal width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
iris.tail(10)

sepal_length  sepal_width  petal_length  petal width         species
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142           5.8          2.7           5.1          1.9  Iris-virginica
143           6.8          3.2           5.9          2.3  Iris-virginica
144           6.7          3.3           5.7          2.5  Iris-virginica
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
iris.info() #show information about the dataframe such as the number of record (entire)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
iris.describe() #show basic statics of the datafram

sepal_length  sepal_width  petal_length  petal width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
iris.shape #show number record and column

(150, 5)

How to access to the values in the Dataframe?

In [ ]:
iris['sepal_length'] #accessing the series name 'sepal_length' , which is a column of dataframe

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
type(iris['sepal_length'])

pandas.core.series.Series

In [ ]:
type(iris)

pandas.core.frame.DataFrame

In [ ]:
iris[["sepal_length","sepal_width"]]

sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [ ]:
type(iris[["sepal_length","sepal_width"]])

pandas.core.frame.DataFrame

In [ ]:
type(iris[["sepal_length"]]) #we use double [][] square brackets for assessing the dataframe

pandas.core.frame.DataFrame

In [ ]:
type(iris["sepal_length"]) #we use one [] square bracket for series

pandas.core.series.Series

In [ ]:
x_df = iris[["sepal_length","sepal_width","petal_length","petal width"]]
x_df

sepal_length  sepal_width  petal_length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
y_df = iris[["species"]]
y_df

species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [ ]:
x_df.iloc[0,:] #access to row 0 of every column [0,:]

sepal_length    5.1
sepal_width     3.5
petal_length    1.4
petal width     0.2
Name: 0, dtype: float64

In [ ]:
x_df.iloc[0,0] #access to row 0 and col 0

5.1

In [ ]:
x_df.iloc[0,2:] #access to row 0 until the end

petal_length    1.4
petal width     0.2
Name: 0, dtype: float64

In [ ]:
x_df.iloc[0,1:3] #access to row 0 and next (only 1 and 2 not include 3)

sepal_width     3.5
petal_length    1.4
Name: 0, dtype: float64

In [ ]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal width',
       'species'],
      dtype='object')

In [ ]:
x_df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal width'], dtype='object')